import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {SessionProvider} from "./components/SessionProvider"
import UserButton from "@/app/components/UserButton";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Js ChatGpt App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <SessionProvider basePath="/api/auth">


    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-2 mdLpx-5`}
      >
   <header className="text-white font-bold bg-green-900 text-2xl flex p-2 mb-3 rounded-b-lg shadow-gray-700 shadow-lg">
       <div className="flex flex-grow">
           <Link href="/">GPT chat</Link>
           <Link href="/about" className="ml-5 font-light">
               About
           </Link>
       </div>

       <div>
           <UserButton/>
       </div>
   </header>

   <div className="flex  col md:flex-row">
       <div className="flex-grow">
           {children}
       </div>
   </div>

      </body>
    </html>


      </SessionProvider>
  );
}
